### ISSUE TITLE
RuntimeError: append_alleles_batch

### ISSUE THREAD

**Issue by cindywen96** [CAST-genomics/haptools#267]
Hi I'm using simgenotype to generate N=10k admix samples from 1KG reference. The breakpoint simulation completes immediately but writing the `admix.pgen` file takes lots of memory and I keep getting the following error. Also it seems the number of written variants change with the number of reference variants. Could you advise on how much memory it takes and is there any limit in number of variants `pgen.append_alleles_batch` could handle? Thank you!
```
[    INFO] Using seed 1234 (sim_genotype.py:359)
[    INFO] Simulating generation 1 (sim_genotype.py:457)
[    INFO] Simulating generation 2 (sim_genotype.py:463)
[    INFO] Simulating generation 3 (sim_genotype.py:463)
[    INFO] Simulating generation 4 (sim_genotype.py:463)
[    INFO] Simulating generation 5 (sim_genotype.py:463)
[    INFO] Simulating generation 6 (sim_genotype.py:463)
[    INFO] Simulating generation 7 (sim_genotype.py:463)
[    INFO] Simulating generation 8 (sim_genotype.py:463)
[    INFO] Simulating generation 9 (sim_genotype.py:463)
[    INFO] Simulating generation 10 (sim_genotype.py:463)
[    INFO] Outputting breakpoint file ./admix/admix.1.bp (sim_genotype.py:503)
[    INFO] Outputting file ./admix/admix.1.pgen (sim_genotype.py:75)
[    INFO] Reading genotypes from 2575 samples and 209824 variants in chunks of size 209824 variants (genotype
s.py:1314)
[    INFO] Writing PVAR records (genotypes.py:1477)
[    INFO] Writing genotypes from 10000 samples and 209824 variants in chunks of size 209824 variants (genotyp
es.py:1553)
Traceback (most recent call last):
  File "/home/unix/zwen/.local/lib/python3.9/site-packages/haptools/data/genotypes.py", line 1582, in write
    pgen.append_alleles_batch(
  File "src/pgenlib/pgenlib.pyx", line 1891, in pgenlib.PgenWriter.append_alleles_batch
  File "src/pgenlib/pgenlib.pyx", line 1940, in pgenlib.PgenWriter.append_alleles_batch
RuntimeError: append_alleles_batch called with allele codes >= allele_ct_limit; you may need to construct the
PgenWriter with a higher allele_ct_limit setting

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/unix/zwen/.local/bin/haptools", line 8, in <module>
    sys.exit(main())
  File "/broad/software/free/Linux/redhat_7_x86_64/pkgs/anaconda3_2022.10/lib/python3.9/site-packages/click/co
re.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/broad/software/free/Linux/redhat_7_x86_64/pkgs/anaconda3_2022.10/lib/python3.9/site-packages/click/co
re.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/broad/software/free/Linux/redhat_7_x86_64/pkgs/anaconda3_2022.10/lib/python3.9/site-packages/click/co
re.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/broad/software/free/Linux/redhat_7_x86_64/pkgs/anaconda3_2022.10/lib/python3.9/site-packages/click/co
re.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/broad/software/free/Linux/redhat_7_x86_64/pkgs/anaconda3_2022.10/lib/python3.9/site-packages/click/co
re.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/unix/zwen/.local/lib/python3.9/site-packages/haptools/__main__.py", line 298, in simgenotype
    output_vcf(
  File "/home/unix/zwen/.local/lib/python3.9/site-packages/haptools/sim_genotype.py", line 223, in output_vcf
    gts.write()
  File "/home/unix/zwen/.local/lib/python3.9/site-packages/haptools/data/genotypes.py", line 1598, in write
    gc.collect()
  File "src/pgenlib/pgenlib.pyx", line 2061, in pgenlib.PgenWriter.__exit__
  File "src/pgenlib/pgenlib.pyx", line 2062, in pgenlib.PgenWriter.__exit__
  File "src/pgenlib/pgenlib.pyx", line 2050, in pgenlib.PgenWriter.close
RuntimeError: PgenWriter.close() called when number of written variants (209381) unequal to initially declared
 value (209824).
```

**Comment by aryarm** [comment]
Hi @cindywen96 !

##  Regarding your issue about memory:
Internally, haptools must store a genotype matrix (numpy array) of size `num_variants` x `num_samples` x 3 bytes. So if you are trying to write out 10000 samples and 209824 variants, that will require 10000 x 209824 x 3 = 6.3 GB
An unfortunate limitation of the pgenlib library that we use for writing PGEN files is that the bytes in the array must be converted to a higher memory data type before they can be written. (Refer to https://github.com/chrchang/plink-ng/issues/234). The higher memory data type requires four times the original memory. So 6.3 x 4 = 25.2 GB :(
To work around this, we've implemented a `--chunk-size N` parameter which can save you memory (at the expense of time) by performing the conversion to a higher memory data type for only `N` variants at a time. The `--chunk-size` parameter is currently available in other haptools commands but not `simgenotype`, so we've created some draft code that will add it to `simgenotype`: https://github.com/CAST-genomics/haptools/issues/267
Can you try out the new `--chunk-size` parameter and let us know if it resolves the issue? You can install the draft code like this:
```
pip install --upgrade --force-reinstall git+https://github.com/cast-genomics/haptools.git@feat/chunk-simgts
```

## Regarding your issue with `allele codes >= allele_ct_limit`:
I think this was fixed in a recent version of haptools and perhaps the reason that this is occurring is because `pip` has installed a newer version of the pgenlib library with an older version of haptools. Which version of haptools and pgenlib are you using right now?
```
pip list | grep -E 'pgenlib|haptools'
```
In any case, I think this issue will also automatically get resolved when you try the draft code, which will have the newest changes to haptools anyway.

**Comment by aryarm** [comment]
Can you help me replicate the error? Can you share your model file and the version of the 1000 Genomes reference that you're using? Also, can you share the command that you're running?

**Comment by cindywen96** [comment]
Sure, here is the command. 1KG ref is a subset of variants on chr1, hg38
```
haptools simgenotype \
    --ref_vcf hg38.unrelate.1.subset.pgen \
    --sample_info sampleSuperPop.tsv \
    --model model.dat \
    --mapdir ../genetic_map/ \
    --out admix.1.pgen \
    --seed 1234 \
    --chroms 1 \
    --chunk-size 10000
```
And here is test [data](https://drive.google.com/file/d/1w7oCXVWPC792NqpU8P-_fC0PguTRM1rQ/view?usp=sharing)

**Comment by aryarm** [comment]
Can you also share the pvar and psam files that correspond with the pgen file?

**Comment by cindywen96** [comment]
Sure, please see additional files attached.
[Archive.zip](https://github.com/user-attachments/files/18246717/Archive.zip)

**Comment by aryarm** [comment]
Ok, thanks! I ran it on my machine and got a different error.

```
RuntimeError: b'PgfiInitPhase1() was called with raw_variant_ct == 166930, but hg38.unrelate.1.subset.pgen contains 188321 variants.\n'
```

Can you also validate that there aren't any issues with your PGEN and PVAR files?

```
plink2 --pfile hg38.unrelate.1.subset --validate
```

**Comment by cindywen96** [comment]
My bad, please use this pgen file attached. plink file contains 166930 variants.
[hg38.unrelate.1.subset.pgen.zip](https://github.com/user-attachments/files/18247153/hg38.unrelate.1.subset.pgen.zip)

**Comment by aryarm** [comment]
@cindywen96, thank you so much for reporting this issue! I was able to replicate it.

It seems like there are actually multiple problems:
1. The code for writing PGEN files has a critical bug in it. This affects anyone trying to write PGEN files with haptools using `--chunk-size`! As far as I can tell, the bug essentially negates the affects of chunking and causes it to use just as much memory as if chunking wasn't used. I resolved this bug in 72a5f88bc107cf977ba752741dbbb03f7700e18a.
2. `simgenotype` is trying to write extra alleles that don't exist in the reference VCF. I haven't figured out why this is happening yet, but I added a more helpful error to catch it in f04ec2b4e6275bb7a527c67d5af93748817269f3.

I'll continue to debug issue 2 and get back to you ASAP once I've figured it out.

@mlamkin7, here are some steps for us to more easily replicate issue 2:
1. Download this file: https://drive.google.com/file/d/1Mm3UfCJdaznQBzksu3OZnfGhb0aWvG_y
2. Untar it in the same directory as the cloned repository: `tar xvzf replicate_simgenotype_err.tar.gz`
3. Run the test: `./simgts-test.py`

**Comment by aryarm** [comment]
@cindywen96, can you download the newest version of the code and try it again?
```
pip install --upgrade --force-reinstall git+https://github.com/cast-genomics/haptools.git@feat/chunk-simgts
```

Last night, @mlamkin7 pushed some code in https://github.com/CAST-genomics/haptools/pull/268/commits/e3db851cd779e72f1c6d344f9d546748ff9eccc0 which should fix issue 2.

What we noticed is that there are variants in your reference file with coordinates past the last coordinate in the map file. Our code had previously been unable to handle that. The new code fixes this by writing the coordinate of the last breakpoint in the `.bp` file as the max int32 value.

https://github.com/CAST-genomics/haptools/blob/e3db851cd779e72f1c6d344f9d546748ff9eccc0/haptools/sim_genotype.py#L369-L372

**Comment by cindywen96** [comment]
Problem solved. Thank you so much!

**Comment by aryarm** [comment]
Thank _you_ for alerting us to this bug and helping us replicate it so easily!

**Comment by cindywen96** [comment]
Hi I have a follow-up question with `--chunk-size`. Would it be possible to, after simulating the break points, read ref genotype also in chunks? Currently it seems only writing simulated genotype is by chunks. Thank you!

**Comment by aryarm** [comment]
sure! I can change the code to do that

I had initially refrained because the 1000 genomes reference is usually quite small in comparison to the simulated genotypes, so I figured that you wouldn't need much memory to load the reference, in comparison to the amount of memory that you'll need to write the simulate genotypes. I guess what I'm trying to say is that: If you're having trouble loading the reference, then it's probably a sign that you won't have enough memory to write the simulated genotypes either? But, if you'd like, I can create a branch with the changes for you to try and then you can let me know if I should merge it

**Comment by cindywen96** [comment]
Thank you so much!

**Comment by aryarm** [comment]
Thanks for the reminder, @mauerjh !

We've just published `v0.6` of haptools. Sorry for the wait!
